export const APP_PATHS = {
  landing: "/",
  signIn: "/sign-in",
  signUp: "/sign-up",
  home: "/home",
  userProfile: "/user/profile",
  createEvent: "/event/create",
  updateEvent: "/event/update",
  createEventItems: "/event/create-items",
  createdConfirm: "/event/created-confirm",
  manageOrders: "/event/manage-orders",
  eventDetail: "/event/detail/:eventId",
  eventCheckout: "/event/checkout/:eventId",
  listMyEvents: "/event/list-my-events",
  listMyPurchases: "/event/list-my-purchases",
  listMyGroups: "/group/list-my-groups",
  groupDetail: "/group/:groupId",
  welcome: "/welcome",
  test: "/test",
} as const;
